apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.vote }}
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote:before
        name: vote
